version: "3.8"
# Compose file build variables set in .env
services:
  supervisor:
    build:
      context: ./build
      args:
        IMAGE_BASE: ${IMAGE_BASE}
        PYTORCH_VERSION: ${PYTORCH_VERSION}
      tags:
        - "ghcr.io/ai-dock/pytorch:${IMAGE_TAG}"
    image: ghcr.io/ai-dock/pytorch:${IMAGE_TAG}
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    devices:
      # For Rclone mount
      - "/dev/fuse:/dev/fuse"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"
    volumes:
      # For Rclone mount
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./config/rclone:/etc/rclone
      # Workspace
      - ./workspace:/workspace:rshared
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - 2222:22
        # Rclone webserver for interactive configuration
        - 53682:53682
    environment:
        # Don't enclose values in quotes
        - WORKSPACE=/workspace/
    env_file: config/env.conf
